supportedCredentialTypes = {
    "ComercioCredencial_jwt_vc_json" = {
        format = "jwt_vc_json"
        cryptographic_binding_methods_supported = ["did"]
        credential_signing_alg_values_supported = ["ES256" , "RSA" , "EdDSA" , "ES256K"]
        credential_definition = {
            type = ["VerifiableCredential", "Credencial Comerç"]
        }
    }
}
